name: code-ql

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  code-ql:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    permissions:
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Initialize CodeQL
      uses: github/codeql-action/init@294a9d92911152fe08befb9ec03e240add280cb3 # v3.26.8
      with:
        build-mode: none
        languages: ${{ matrix.language }}
        queries: security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@294a9d92911152fe08befb9ec03e240add280cb3 # v3.26.8
      with:
        category: '/language:${{ matrix.language }}'
