name: dependabot-approve

on: pull_request_target

permissions:
  contents: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false && github.event.pull_request.user.login == 'dependabot[bot]'

    steps:

      - name: Get dependabot metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0
        id: dependabot-metadata

      - name: Generate GitHub application token
        id: generate-application-token
        uses: peter-murray/workflow-application-token-action@8e4e6fbf6fcc8a272781d97597969d21b3812974 # v4.0.0
        with:
          application_id: ${{ secrets.REVIEWER_APPLICATION_ID }}
          application_private_key: ${{ secrets.REVIEWER_APPLICATION_PRIVATE_KEY }}
          permissions: "contents:write, pull_requests:write, workflows:write"

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Approve pull request and enable auto-merge
        shell: bash
        # Only approve pull requests if there is only exactly one dependency, and it is only of those listed below.
        # If using grouped Dependabot updates, then you will need to update this condition to verify that all of
        # the dependencies that were updated are ones that are trusted. Otherwise a group that contains a single
        # trusted dependency amongst others that require manual review will be approved automatically.
        # See https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/ for more information.
        if: |
          steps.dependabot-metadata.outputs.dependency-names == 'actions/cache' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/checkout' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/dependency-review-action' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/setup-dotnet' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/setup-node' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/upload-artifact' ||
          steps.dependabot-metadata.outputs.dependency-names == 'dependabot/fetch-metadata' ||
          steps.dependabot-metadata.outputs.dependency-names == 'github/codeql-action' ||
          steps.dependabot-metadata.outputs.dependency-names == 'Microsoft.NET.Test.Sdk' ||
          steps.dependabot-metadata.outputs.dependency-names == 'Microsoft.TypeScript.MSBuild' ||
          steps.dependabot-metadata.outputs.dependency-names == 'typescript'
        env:
          GH_TOKEN: ${{ steps.generate-application-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr checkout "${PR_URL}"
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "${PR_URL}" && gh pr merge --auto --squash "${PR_URL}"
          fi
