name: dependabot-approve

on: pull_request_target # zizmor: ignore[dangerous-triggers] Guarded by dependabot/fetch-metadata

permissions: {}

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    if: github.event.repository.fork == false && github.event.pull_request.user.login == 'dependabot[bot]'

    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}
      cancel-in-progress: false

    environment:
      name: change-approval
      deployment: false

    permissions:
      contents: read

    steps:

      - name: Get dependabot metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        id: dependabot-metadata

      - name: Generate GitHub application token
        id: generate-application-token
        # Only approve pull requests if there is only exactly one dependency, and it is only of those listed below.
        # If using grouped Dependabot updates, then you will need to update this condition to verify that all of
        # the dependencies that were updated are ones that are trusted. Otherwise a group that contains a single
        # trusted dependency amongst others that require manual review will be approved automatically.
        # See https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/ for more information.
        if: |
          steps.dependabot-metadata.outputs.dependency-names == 'actions/checkout' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/create-github-app-token' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/dependency-review-action' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/setup-dotnet' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/setup-node' ||
          steps.dependabot-metadata.outputs.dependency-names == 'actions/upload-artifact' ||
          steps.dependabot-metadata.outputs.dependency-names == 'dependabot/fetch-metadata' ||
          steps.dependabot-metadata.outputs.dependency-names == 'github/codeql-action' ||
          steps.dependabot-metadata.outputs.dependency-names == 'Microsoft.NET.Test.Sdk' ||
          steps.dependabot-metadata.outputs.dependency-names == 'Microsoft.TypeScript.MSBuild' ||
          steps.dependabot-metadata.outputs.dependency-names == 'typescript'
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.REVIEWER_APPLICATION_ID }}
          private-key: ${{ secrets.REVIEWER_APPLICATION_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-workflows: write

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: steps.generate-application-token.outputs.token != ''
        with:
          persist-credentials: false

      - name: Approve pull request and enable auto-merge
        if: steps.generate-application-token.outputs.token != ''
        shell: bash
        env:
          GH_TOKEN: ${{ steps.generate-application-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          if [ "$(gh pr view "${PR_NUMBER}" --json reviewDecision --jq .reviewDecision --repo "${GITHUB_REPOSITORY}")" != "APPROVED" ];
          then gh pr review --approve "${PR_NUMBER}" --repo "${GITHUB_REPOSITORY}" && gh pr merge --auto --squash "${PR_NUMBER}" --repo "${GITHUB_REPOSITORY}"
          fi
