# This workflow uses a reusable workfrom from martincostello/update-dotnet-sdk
# which uses the martincostello/update-dotnet-sdk GitHub Action and the dotnet-outdated
# global tool to update the .NET SDK and Microsoft-published NuGet packages for
# the application in this repository to the latest patch version on a weekly basis.

name: update-dotnet-sdk

on:

  # Run at 2100 UTC on Tuesday every week to pick up any updates from
  # Patch Tuesday which occur on the second Tuesday of the month (PST).
  # If you apply this workflow to multiple repositories, you may wish
  # to offset the schedule for each repository by an appropriate amount
  # to avoid your applications having their updates deployed simultaneously
  # if you practice continuous deployment without manual approval/gating.
  schedule:
    - cron:  '00 21 * * TUE'

  # Also support running the workflow manually on-demand.
  workflow_dispatch:

# Set the minumum permissions for GITHUB_TOKEN as we are using a GitHub application to perform the updates.
permissions:
  contents: read

# Using a personal access token or a GitHub app is recommended instead of using GITHUB_TOKEN, otherwise
# pull requests opened by this workflow, and commits pushed, will not queue your CI status checks if you
# use GitHub Actions for your CI.
# See https://docs.github.com/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
#
# The Git commit user name and email are set as variables in the organization or repository settings.
# See https://docs.github.com/actions/learn-github-actions/variables.
#
# You can obtain the user name and email for the GitHub app by running the following command using the
# GitHub CLI (https://cli.github.com/) in a terminal and substituting the values as shown below:
#
# app_name="YOUR_GITHUB_APP_NAME"
# echo "Git user name: ${app_name}[bot]"
# echo "Git user email: $(gh api "/users/${app_name}[bot]" --jq ".id")+${app_name}[bot]@users.noreply.github.com"
jobs:
  update-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@bba9c5d796cf9e84046ae0cb42f7dd33bde568f3 # v2.1.4
    with:
      labels: "dependencies,.NET"
      user-email: ${{ vars.GIT_COMMIT_USER_EMAIL }}
      user-name: ${{ vars.GIT_COMMIT_USER_NAME }}
    secrets:
      application-id: ${{ secrets.UPDATER_APPLICATION_ID }}
      application-private-key: ${{ secrets.UPDATER_APPLICATION_PRIVATE_KEY }}

  add-security-label:
    needs: update-sdk
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if : |
      needs.update-sdk.outputs.sdk-updated =='true' &&
      needs.update-sdk.outputs.security == 'true'
    steps:
    - name: Add security label
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr edit "${{ needs.update-sdk.outputs.pull-request-html-url }}" --add-label security
