name: update-dotnet-sdk

# Using a real user/email is recommended instead of using GITHUB_TOKEN, otherwise pull
# requests opened by this workflow, and commits pushed, will not queue your CI status checks.
# See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow.
env:
  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_COMMIT_USER_NAME: 'github-actions[bot]'
  TERM: xterm

on:
  # Run at 2100 UTC on Tuesday every week to pick up any updates from
  # Patch Tuesday which occur on the second Tuesday of the month (PST).
  schedule:
    - cron:  '00 21 * * TUE'
  # Also support running the workflow manually on-demand.
  workflow_dispatch:

# Configure the GitHub access token to be able to clone
# the repository, push a branch containing the SDK update,
# and then open a pull request to merge the change. This
# can be changed to just 'contents:read' if you do not use GITHUB_TOKEN.
permissions:
  contents: write
  pull-requests: write

jobs:

  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork == false }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ env.ACCESS_TOKEN }}

    - name: Update .NET SDK
      id: update-dotnet-sdk
      uses: martincostello/update-dotnet-sdk@v2
      with:
        labels: "dependencies,.NET"
        repo-token: ${{ env.ACCESS_TOKEN }}
        user-email: ${{ env.GIT_COMMIT_USER_EMAIL }}
        user-name: ${{ env.GIT_COMMIT_USER_NAME }}

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      if : ${{ steps.update-dotnet-sdk.outputs.sdk-updated == 'true' }}

    - name: Update NuGet packages
      if : ${{ steps.update-dotnet-sdk.outputs.sdk-updated == 'true' }}
      shell: pwsh
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
        NUGET_XMLDOC_MODE: skip
      run: |
        $ErrorActionPreference = "Stop"

        dotnet tool install --global dotnet-outdated-tool

        $tempPath = [System.IO.Path]::GetTempPath()
        $updatesPath = (Join-Path $tempPath "dotnet-outdated.json")

        Write-Host "Checking for .NET NuGet package(s) to update..."

        dotnet outdated `
          --upgrade `
          --version-lock Major `
          --output $updatesPath `
          --include "Microsoft.AspNetCore." `
          --include "Microsoft.EntityFrameworkCore." `
          --include "Microsoft.Extensions." `
          --include "System."

        $dependencies = @()

        if (Test-Path $updatesPath) {
          $dependencies = `
            Get-Content -Path $updatesPath | `
            ConvertFrom-Json | `
            Select-Object -ExpandProperty projects | `
            Select-Object -ExpandProperty TargetFrameworks | `
            Select-Object -ExpandProperty Dependencies | `
            Sort-Object -Property Name -Unique
        }

        if ($dependencies.Count -gt 0) {
          Write-Host "Found $($dependencies.Count) .NET NuGet package(s) to update." -ForegroundColor Green

          $commitMessageLines = @()

          if ($dependencies.Count -eq 1) {
            $commitMessageLines += "Bump $($dependencies[0].Name) from $($dependencies[0].ResolvedVersion) to $($dependencies[0].LatestVersion)"
            $commitMessageLines += ""
            $commitMessageLines += "Bumps $($dependencies[0].Name) from $($dependencies[0].ResolvedVersion) to $($dependencies[0].LatestVersion)."
          } else {
            $commitMessageLines += "Bump .NET NuGet packages"
            $commitMessageLines += ""
            $commitMessageLines += "Bumps .NET dependencies to their latest versions for the .NET ${{ steps.update-dotnet-sdk.outputs.sdk-version }} SDK."
            $commitMessageLines += ""
            foreach ($dependency in $dependencies) {
              $commitMessageLines += "Bumps $($dependency.Name) from $($dependency.ResolvedVersion) to $($dependency.LatestVersion)."
            }
          }

          foreach ($dependency in $dependencies) {
            $commitMessageLines += "- dependency-name: $($dependency.Name)"
            $commitMessageLines += "  dependency-type: direct:production"
            $commitMessageLines += "  update-type: version-update:semver-$($dependency.UpgradeSeverity.ToLowerInvariant())"
          }

          $commitMessageLines += "..."
          $commitMessageLines += ""
          $commitMessageLines += ""

          $commitMessage = $commitMessageLines -join "`n"

          git config user.email "${{ env.GIT_COMMIT_USER_EMAIL }}"
          git config user.name "${{ env.GIT_COMMIT_USER_NAME }}"

          git add .
          git commit -m $commitMessage
          git push

          Write-Host "Pushed update to $($dependencies.Count) NuGet package(s)." -ForegroundColor Green
        }
        else {
          Write-Host "There are no .NET NuGet packages to update." -ForegroundColor Green
        }
